# Generated by Django 2.1.2 on 2018-11-03 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20181103_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_invoice', to='invoice.Payment', verbose_name='款项'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='对方'),
        ),
    ]
