# Generated by Django 2.1.2 on 2018-12-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方'), ('cart', '车'), ('part', '夹'), ('piece', '件')], default='m2', max_length=10, verbose_name='计量单位'),
        ),
    ]
