# Generated by Django 2.1.2 on 2018-12-19 07:51

from django.db import migrations
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_invoiceitem_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assign',
            options={'verbose_name': '收款分配'},
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
    ]
