# Generated by Django 2.1.2 on 2018-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_auto_20181228_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='usage',
            field=models.CharField(max_length=50, verbose_name='款项用途'),
        ),
    ]
