# Generated by Django 2.1.2 on 2019-01-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_auto_20181230_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
            ],
            options={
                'verbose_name': '采购账单',
                'proxy': True,
                'indexes': [],
            },
            bases=('invoice.invoice',),
        ),
    ]
