# Generated by Django 2.1.2 on 2019-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_expensesinvoice_salesinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='desc',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='账号'),
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='银行名称'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='账户人'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, verbose_name='账户名称'),
        ),
    ]
