# Generated by Django 2.1.2 on 2019-03-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_auto_20190110_0645'),
        ('invoice', '0026_auto_20190110_0643'),
    ]

    operations = [
    ]
