# Generated by Django 2.1.2 on 2019-03-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0026_auto_20190110_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created',), 'permissions': (('can_draft', '设为草稿'), ('can_cancel', '设为取消')), 'verbose_name': '账单'},
        ),
    ]
