# Generated by Django 2.1.2 on 2019-03-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_merge_20190313_0331'),
        ('invoice', '0027_auto_20190313_0252'),
    ]

    operations = [
    ]
