# Generated by Django 2.1.2 on 2019-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0028_merge_20190313_0519'),
        ('invoice', '0028_auto_20190313_0631'),
    ]

    operations = [
    ]
