# Generated by Django 2.1.7 on 2019-03-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_log',
            field=models.BooleanField(default=True, verbose_name='操作日志'),
        ),
    ]
