# Generated by Django 2.1.2 on 2018-10-29 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='库位名称')),
                ('usage', models.CharField(choices=[('supplier', '供应商库位'), ('customer', '客户库位'), ('production', '生产库位'), ('internal', '存货库位'), ('inventory', '盘点库位')], max_length=50, verbose_name='库位用途')),
                ('is_virtual', models.BooleanField(verbose_name='虚拟库位')),
                ('desc', models.TextField(verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='stock.Location', verbose_name='上级库位')),
            ],
            options={
                'verbose_name': '库位信息',
            },
        ),
        migrations.CreateModel(
            name='StockTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('product_id', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_trace_from', to='stock.Location', verbose_name='库位')),
                ('location_dest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_trace_to', to='stock.Location', verbose_name='目标库位')),
                ('order_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock_trace', to='contenttypes.ContentType')),
                ('product_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_trace', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '库存轨迹',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=20, verbose_name='缩写名称')),
            ],
            options={
                'verbose_name': '仓库信息',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='stock.Warehouse', verbose_name='所属仓库'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'name')},
        ),
    ]
