# Generated by Django 2.1.2 on 2018-10-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_activate',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='合作伙伴'),
        ),
    ]
