# Generated by Django 2.1.2 on 2018-11-01 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181101_0453'),
        ('stock', '0002_auto_20181029_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktrace',
            name='product_content_type',
        ),
        migrations.RemoveField(
            model_name='stocktrace',
            name='product_id',
        ),
        migrations.AddField(
            model_name='stocktrace',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_trace', to='product.Product'),
            preserve_default=False,
        ),
    ]
