# Generated by Django 2.1.2 on 2018-11-05 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_packagelist_packagelistitem_slab'),
        ('stock', '0003_auto_20181101_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('reserve_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预留数量')),
                ('reserve_piece', models.IntegerField(blank=True, default=1, null=True, verbose_name='预留件')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], max_length=6, verbose_name='单位')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='stocktrace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktrace',
            name='piece',
            field=models.IntegerField(default=1, verbose_name='件'),
        ),
        migrations.AddField(
            model_name='stocktrace',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktrace',
            name='state',
            field=models.CharField(choices=[('lock', '锁货'), ('done', '完成'), ('cancel', '取消')], default='lock', max_length=10, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_activate': True, 'is_virtual': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='stock.Location', verbose_name='上级库位'),
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(limit_choices_to={'is_virtual': False}, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.Location'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'location')},
        ),
    ]
