# Generated by Django 2.1.2 on 2018-11-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20181105_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktrace',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='stocktrace',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stocktrace',
            name='state',
        ),
    ]
