# Generated by Django 2.1.2 on 2018-11-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20181105_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_main',
            field=models.BooleanField(default=False, help_text='主库位，只有在创建warehouse时一并创建', verbose_name='主库位'),
        ),
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='虚拟库位'),
        ),
    ]
