# Generated by Django 2.1.2 on 2018-11-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20181106_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_production',
            field=models.BooleanField(default=False, verbose_name='有生产活动'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='stock.Warehouse', verbose_name='所属仓库'),
        ),
    ]
