# Generated by Django 2.1.2 on 2018-11-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20181107_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='reserve_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='预留件'),
        ),
    ]
