# Generated by Django 2.1.2 on 2018-11-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20181107_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='is_production',
            field=models.BooleanField(default=False, verbose_name='有生产活动'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='partner.Partner', verbose_name='合作伙伴'),
        ),
    ]
