# Generated by Django 2.1.2 on 2018-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20181125_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='reserve_piece',
            field=models.IntegerField(default=0, verbose_name='预留件'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reserve_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预留数量'),
        ),
    ]
