# Generated by Django 2.1.2 on 2018-12-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20181126_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktrace',
            old_name='order_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='stocktrace',
            old_name='order_id',
            new_name='object_id',
        ),
    ]
