# Generated by Django 2.1.2 on 2019-01-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20181212_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalStockTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='编号')),
                ('address', models.CharField(max_length=20, verbose_name='仓库')),
                ('date', models.DateField(verbose_name='日期')),
                ('part', models.SmallIntegerField(verbose_name='夹')),
                ('piece', models.SmallIntegerField(verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('uom', models.CharField(max_length=10, verbose_name='单位')),
                ('stock_trace', models.CharField(max_length=10, verbose_name='事务')),
            ],
            options={
                'verbose_name': '旧数据库存事务',
            },
        ),
    ]
