# Generated by Django 2.1.2 on 2019-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_originalstocktrace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalstocktrace',
            name='part',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='夹'),
        ),
        migrations.AlterField(
            model_name='originalstocktrace',
            name='piece',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='件'),
        ),
    ]
