# Generated by Django 2.1.2 on 2019-01-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20190112_0843'),
        ('stock', '0015_auto_20190114_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='originalstocktrace',
            name='name',
        ),
        migrations.AddField(
            model_name='originalstocktrace',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Block', verbose_name='编号'),
        ),
    ]
