# Generated by Django 2.1.2 on 2019-01-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20190114_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originalstocktrace',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_stock_trace', to='product.Block', verbose_name='编号'),
        ),
    ]
