# Generated by Django 2.1.2 on 2019-01-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_auto_20190114_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalstocktrace',
            options={'ordering': ('-date',), 'verbose_name': '旧数据库存事务'},
        ),
    ]
