# Generated by Django 2.1.2 on 2019-01-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20190115_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='缩写名称'),
        ),
    ]
