# Generated by Django 2.1.2 on 2019-02-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20190121_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='_address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
    ]
