# Generated by Django 2.1.2 on 2019-03-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_warehouse__address'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='main_height',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='高'),
        ),
        migrations.AddField(
            model_name='stock',
            name='main_long',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='长'),
        ),
        migrations.AddField(
            model_name='stock',
            name='main_width',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='宽'),
        ),
    ]
