# Generated by Django 2.1.7 on 2019-03-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='事务名称')),
                ('time', models.DateTimeField(verbose_name='开始时间')),
                ('is_complete', models.BooleanField(default=False, verbose_name='完成')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
            ],
            options={
                'verbose_name': '提醒事务',
            },
            bases=(public.models.HasChangedMixin, models.Model),
        ),
    ]
