# Generated by Django 2.1.7 on 2019-03-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-time', '-updated', '-created'], 'verbose_name': '提醒事务'},
        ),
    ]
