# Generated by Django 2.1.7 on 2019-03-20 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20190320_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='complete_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_complete_entry', to=settings.AUTH_USER_MODEL, verbose_name='完成人'),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='handler',
        ),
        migrations.AddField(
            model_name='tasks',
            name='handler',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks_handler', to=settings.AUTH_USER_MODEL, verbose_name='指派经办人'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='time',
            field=models.DateTimeField(verbose_name='提醒时间'),
        ),
    ]
