# Generated by Django 2.1.7 on 2019-03-29 06:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('product', '0003_auto_20190314_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='taggit',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
