# Generated by Django 2.1.7 on 2019-03-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_block_taggit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='taggit',
            new_name='tags',
        ),
    ]
