# Generated by Django 2.1.2 on 2019-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_wxconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxconfig',
            name='agent_id',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
