# Generated by Django 2.1.2 on 2018-10-29 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='批次编号')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量')),
                ('long', models.IntegerField(null=True, verbose_name='长')),
                ('width', models.IntegerField(null=True, verbose_name='宽')),
                ('high', models.IntegerField(null=True, verbose_name='高')),
                ('m3', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='立方')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], max_length=10, verbose_name='计量单位')),
            ],
            options={
                'verbose_name': '荒料',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='品种名称')),
                ('created', models.DateField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '品种信息',
                'verbose_name_plural': '品种信息',
            },
        ),
        migrations.CreateModel(
            name='Quarry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='矿口名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述信息')),
                ('created', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '矿口信息',
                'verbose_name_plural': '矿口信息',
            },
        ),
        migrations.CreateModel(
            name='SemiFinishedSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='厚度规格')),
                ('long', models.PositiveSmallIntegerField(blank=True, help_text='单位cm', verbose_name='长')),
                ('high', models.PositiveSmallIntegerField(blank=True, help_text='单位cm', verbose_name='高')),
            ],
            options={
                'verbose_name': '毛板',
            },
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数量')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='厚度规格')),
                ('long', models.PositiveSmallIntegerField(help_text='单位cm', verbose_name='长')),
                ('high', models.PositiveSmallIntegerField(help_text='单位cm', verbose_name='高')),
                ('kl1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='长1')),
                ('kl2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='长2')),
                ('kh1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='高1')),
                ('kh2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='高2')),
            ],
            options={
                'verbose_name': '板材',
            },
        ),
        migrations.CreateModel(
            name='SN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='编号')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Batch', verbose_name='批次')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='品种名称')),
                ('quarry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Quarry', verbose_name='矿口')),
            ],
            options={
                'verbose_name': '荒料编号',
            },
        ),
        migrations.AddField(
            model_name='slab',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_slab', to='product.SN', verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='semifinishedslab',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_semifinishedslab', to='product.SN', verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='block',
            name='sn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_block', to='product.SN', verbose_name='编号'),
        ),
    ]
