# Generated by Django 2.1.7 on 2019-03-13 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slab',
            name='stock',
            field=models.ForeignKey(blank=True, limit_choices_to={'location__is_virtual': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Block', verbose_name='荒料编号'),
        ),
        migrations.AddField(
            model_name='packagelistitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.PackageList', verbose_name='码单'),
        ),
        migrations.AddField(
            model_name='packagelistitem',
            name='slab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_list', to='product.Slab', verbose_name='板材'),
        ),
        migrations.AddField(
            model_name='packagelist',
            name='from_package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='创建自'),
        ),
        migrations.AddField(
            model_name='packagelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_listed', to='product.Product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='draftpackagelistitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.DraftPackageList', verbose_name='码单'),
        ),
        migrations.AddField(
            model_name='draftpackagelist',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftpackagelist_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='product.Category', verbose_name='上级分类'),
        ),
        migrations.AddField(
            model_name='block',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Batch', verbose_name='批次'),
        ),
        migrations.AddField(
            model_name='block',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='品种名称'),
        ),
        migrations.AddField(
            model_name='block',
            name='quarry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Quarry', verbose_name='矿口'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('block', 'type', 'thickness')},
        ),
    ]
