# Generated by Django 2.1.2 on 2018-10-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sn',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Batch', verbose_name='批次'),
        ),
        migrations.AlterField(
            model_name='sn',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='品种名称'),
        ),
        migrations.AlterField(
            model_name='sn',
            name='quarry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Quarry', verbose_name='矿口'),
        ),
    ]
