# Generated by Django 2.1.2 on 2018-10-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181029_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': '批次', 'verbose_name_plural': '批次'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '荒料', 'verbose_name_plural': '荒料'},
        ),
        migrations.AlterModelOptions(
            name='semifinishedslab',
            options={'verbose_name': '毛板', 'verbose_name_plural': '毛板'},
        ),
        migrations.AlterModelOptions(
            name='slab',
            options={'verbose_name': '板材', 'verbose_name_plural': '板材'},
        ),
        migrations.AlterModelOptions(
            name='sn',
            options={'verbose_name': '荒料编号', 'verbose_name_plural': '荒料编号'},
        ),
    ]
