# Generated by Django 2.1.2 on 2018-10-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181029_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='high',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='semifinishedslab',
            old_name='high',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='slab',
            old_name='high',
            new_name='height',
        ),
    ]
