# Generated by Django 2.1.2 on 2018-10-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20181030_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='sn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_block', to='product.SN', verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='semifinishedslab',
            name='sn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_semifinishedslab', to='product.SN', verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='slab',
            name='sn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_slab', to='product.SN', verbose_name='编号'),
        ),
    ]
