# Generated by Django 2.1.2 on 2018-10-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181031_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='block',
            name='long',
            field=models.IntegerField(blank=True, null=True, verbose_name='长'),
        ),
        migrations.AlterField(
            model_name='block',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方'),
        ),
        migrations.AlterField(
            model_name='block',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='block',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
        migrations.AlterField(
            model_name='block',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽'),
        ),
        migrations.AlterField(
            model_name='semifinishedslab',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='slab',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='数量'),
        ),
    ]
