# Generated by Django 2.1.2 on 2018-10-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20181031_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='数量'),
        ),
    ]
