# Generated by Django 2.1.2 on 2018-11-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20181031_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='编号')),
                ('type', models.CharField(choices=[('block', '荒料'), ('semi_slab', '毛板'), ('slab', '板材')], default='block', max_length=10, verbose_name='类型')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='厚度规格')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量')),
                ('long', models.IntegerField(blank=True, null=True, verbose_name='长')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高')),
                ('m3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方')),
                ('block_uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='荒料计量单位')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '荒料编号',
                'verbose_name_plural': '荒料编号',
            },
        ),
        migrations.RemoveField(
            model_name='block',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='semifinishedslab',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='slab',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='sn',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='sn',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sn',
            name='quarry',
        ),
    ]
