# Generated by Django 2.1.2 on 2018-11-01 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181101_0453'),
        ('purchase', '0015_auto_20181101_0453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='SemiFinishedSlab',
        ),
        migrations.DeleteModel(
            name='Slab',
        ),
        migrations.DeleteModel(
            name='SN',
        ),
        migrations.AddField(
            model_name='product',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Batch', verbose_name='批次'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='品种名称'),
        ),
        migrations.AddField(
            model_name='product',
            name='quarry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Quarry', verbose_name='矿口'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'type', 'thickness')},
        ),
    ]
