# Generated by Django 2.1.2 on 2018-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20181101_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=False, verbose_name='启用'),
        ),
    ]
