# Generated by Django 2.1.2 on 2018-11-05 06:40

from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '码单',
            },
        ),
        migrations.CreateModel(
            name='PackageListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.SmallIntegerField(verbose_name='夹号')),
                ('line', public.fields.LineField(blank=True, verbose_name='序号')),
            ],
            options={
                'verbose_name': '码单项',
            },
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.SmallIntegerField(help_text='单位cm', verbose_name='长')),
                ('height', models.SmallIntegerField(help_text='单位cm', verbose_name='高')),
                ('kl1', models.SmallIntegerField(blank=True, null=True, verbose_name='长1')),
                ('kl2', models.SmallIntegerField(blank=True, null=True, verbose_name='长2')),
                ('kh1', models.SmallIntegerField(blank=True, null=True, verbose_name='高1')),
                ('kh2', models.SmallIntegerField(blank=True, null=True, verbose_name='高2')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='面积(m2)')),
                ('part_number', models.SmallIntegerField(verbose_name='夹号')),
                ('line', public.fields.LineField(blank=True, verbose_name='序号')),
                ('product', models.ForeignKey(limit_choices_to={'type': 'slab'}, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='板材')),
            ],
            options={
                'verbose_name': '板材',
                'verbose_name_plural': '板材',
            },
        ),
    ]
