# Generated by Django 2.1.2 on 2018-11-05 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_packagelist_packagelistitem_slab'),
        ('stock', '0004_auto_20181105_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='slab',
            name='reserve_stock',
            field=models.ForeignKey(blank=True, limit_choices_to={'location__is_virtual': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserve_slabs', to='product.Stock'),
        ),
        migrations.AddField(
            model_name='slab',
            name='stock',
            field=models.ForeignKey(blank=True, limit_choices_to={'location__is_virtual': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slabs', to='product.Stock'),
        ),
        migrations.AddField(
            model_name='packagelistitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.PackageList', verbose_name='码单'),
        ),
        migrations.AddField(
            model_name='packagelistitem',
            name='slab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_list', to='product.Slab', verbose_name='板材'),
        ),
        migrations.AddField(
            model_name='packagelist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_listed', to='product.Product', verbose_name='产品'),
        ),
    ]
