# Generated by Django 2.1.2 on 2018-11-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20181105_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activate',
        ),
    ]
