# Generated by Django 2.1.2 on 2018-11-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='编号'),
        ),
    ]
