# Generated by Django 2.1.2 on 2018-11-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_auto_20181126_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draftpackagelist_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '草稿码单',
            },
        ),
        migrations.CreateModel(
            name='DraftPackageListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.SmallIntegerField(help_text='单位cm', verbose_name='长')),
                ('height', models.SmallIntegerField(help_text='单位cm', verbose_name='高')),
                ('kl1', models.SmallIntegerField(blank=True, null=True, verbose_name='长1')),
                ('kl2', models.SmallIntegerField(blank=True, null=True, verbose_name='长2')),
                ('kh1', models.SmallIntegerField(blank=True, null=True, verbose_name='高1')),
                ('kh2', models.SmallIntegerField(blank=True, null=True, verbose_name='高2')),
                ('part_number', models.SmallIntegerField(verbose_name='夹号')),
                ('line', public.fields.LineField(blank=True, verbose_name='序号')),
                ('package_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.DraftPackageList', verbose_name='码单')),
            ],
            options={
                'verbose_name': '草稿码单行',
            },
        ),
        migrations.AlterModelOptions(
            name='slab',
            options={},
        ),
        migrations.RenameField(
            model_name='packagelistitem',
            old_name='item',
            new_name='package_list',
        ),
        migrations.RemoveField(
            model_name='slab',
            name='product',
        ),
        migrations.RemoveField(
            model_name='slab',
            name='quantity',
        ),
    ]
