# Generated by Django 2.1.2 on 2018-11-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20181128_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpackagelistitem',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'slab'}, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='板材'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slab',
            name='product',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'slab'}, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='板材'),
            preserve_default=False,
        ),
    ]
