# Generated by Django 2.1.2 on 2018-11-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20181128_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftpackagelistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='slab',
            name='product',
        ),
    ]
