# Generated by Django 2.1.2 on 2018-11-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20181128_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpackagelistitem',
            name='line_from',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='从'),
        ),
        migrations.AddField(
            model_name='draftpackagelistitem',
            name='line_to',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='到'),
        ),
        migrations.AddField(
            model_name='draftpackagelistitem',
            name='piece',
            field=models.SmallIntegerField(default=1, verbose_name='件'),
        ),
    ]
