# Generated by Django 2.1.2 on 2018-11-29 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20181129_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftpackagelistitem',
            old_name='package_list',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='packagelistitem',
            old_name='package_list',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='draftpackagelistitem',
            name='line_from',
        ),
        migrations.RemoveField(
            model_name='draftpackagelistitem',
            name='line_to',
        ),
        migrations.RemoveField(
            model_name='draftpackagelistitem',
            name='piece',
        ),
    ]
