# Generated by Django 2.1.2 on 2018-11-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20181129_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slab',
            options={'ordering': ('part_number', 'line')},
        ),
        migrations.AlterField(
            model_name='draftpackagelistitem',
            name='height',
            field=models.SmallIntegerField(help_text='cm', verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='draftpackagelistitem',
            name='long',
            field=models.SmallIntegerField(help_text='cm', verbose_name='长'),
        ),
        migrations.AlterField(
            model_name='slab',
            name='height',
            field=models.SmallIntegerField(help_text='cm', verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='slab',
            name='long',
            field=models.SmallIntegerField(help_text='cm', verbose_name='长'),
        ),
    ]
