# Generated by Django 2.1.2 on 2018-12-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20181129_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='semi_slab_single_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='毛板单件平方'),
        ),
    ]
