# Generated by Django 2.1.2 on 2018-12-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_semi_slab_single_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slab',
            name='line',
            field=models.SmallIntegerField(verbose_name='序号'),
        ),
    ]
