# Generated by Django 2.1.2 on 2018-12-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20181202_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='编号')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量')),
                ('long', models.IntegerField(blank=True, null=True, verbose_name='长')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='高')),
                ('m3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='荒料计量单位')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Batch', verbose_name='批次')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='品种名称')),
                ('quarry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Quarry', verbose_name='矿口')),
            ],
            options={
                'verbose_name': '荒料资料',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品资料', 'verbose_name_plural': '产品资料'},
        ),
        migrations.AddField(
            model_name='product',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Block', verbose_name='荒料编号'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='long',
        ),
        migrations.RemoveField(
            model_name='product',
            name='m3',
        ),
        # migrations.RemoveField(
        #     model_name='product',
        #     name='name',
        # ),
        migrations.RemoveField(
            model_name='product',
            name='quarry',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('block', 'type', 'thickness')},
        ),
    ]
