# Generated by Django 2.1.2 on 2018-12-03 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20181203_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
