# Generated by Django 2.1.2 on 2018-12-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_remove_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slab',
            name='stock',
            field=models.ForeignKey(blank=True, limit_choices_to={'location__is_virtual': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.Stock'),
        ),
    ]
