# Generated by Django 2.1.2 on 2018-12-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20181204_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagelistitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.PackageList', verbose_name='码单'),
        ),
    ]
