# Generated by Django 2.1.2 on 2018-12-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20181205_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slab',
            name='reserve_stock',
        ),
        migrations.AddField(
            model_name='slab',
            name='is_reserve',
            field=models.BooleanField(default=False, verbose_name='锁库'),
        ),
    ]
