# Generated by Django 2.1.2 on 2018-12-08 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20181206_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelist',
            name='from_package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='创建自'),
        ),
    ]
