# Generated by Django 2.1.2 on 2018-12-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_draftpackagelist_thickness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagelistitem',
            options={'ordering': ('part_number', 'line'), 'verbose_name': '码单项'},
        ),
        migrations.AddField(
            model_name='draftpackagelist',
            name='from_path',
            field=models.URLField(blank=True, null=True, verbose_name='返回页面'),
        ),
    ]
