# Generated by Django 2.1.2 on 2018-12-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20181217_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slab',
            options={'verbose_name': '板材', 'verbose_name_plural': '板材'},
        ),
    ]
