# Generated by Django 2.1.2 on 2018-12-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20181217_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagelist',
            name='return_path',
            field=models.URLField(blank=True, null=True, verbose_name='返回链接'),
        ),
    ]
