# Generated by Django 2.1.2 on 2019-01-03 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_packagelist_return_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('product.product',),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='product.Category', verbose_name='上级分类'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='分类'),
        ),
    ]
