# Generated by Django 2.1.2 on 2019-01-03 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20190103_0716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyProduct',
        ),
    ]
