# Generated by Django 2.1.2 on 2019-01-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_delete_proxyproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '品种分类', 'verbose_name_plural': '品种分类'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='quarry',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='描述信息'),
        ),
    ]
