# Generated by Django 2.1.2 on 2019-01-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20190103_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='品种名称'),
            preserve_default=False,
        ),
    ]
