# Generated by Django 2.1.2 on 2019-01-06 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20190103_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='品种名称'),
        ),
    ]
