# Generated by Django 2.1.2 on 2019-01-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_auto_20190106_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['category', 'batch', 'name'], 'verbose_name': '荒料资料'},
        ),
    ]
