# Generated by Django 2.1.2 on 2019-03-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20190112_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='_slab_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='出材率'),
        ),
        migrations.AddField(
            model_name='block',
            name='old_system_slab_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='旧系统出材率'),
        ),
    ]
