# Generated by Django 2.1.7 on 2019-03-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('partner', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='库位名称')),
                ('is_main', models.BooleanField(default=False, help_text='主库位，只有在创建warehouse时一并创建', verbose_name='主库位')),
                ('usage', models.CharField(choices=[('supplier', '供应商库位'), ('customer', '客户库位'), ('production', '生产库位'), ('internal', '存货库位'), ('inventory', '盘点库位')], max_length=50, verbose_name='库位用途')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='虚拟库位')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_activate', models.BooleanField(default=True, verbose_name='启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_activate': True, 'is_virtual': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='stock.Location', verbose_name='上级库位')),
            ],
            options={
                'verbose_name': '库位信息',
            },
        ),
        migrations.CreateModel(
            name='OriginalStockTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, verbose_name='仓库')),
                ('date', models.DateField(verbose_name='日期')),
                ('part', models.SmallIntegerField(blank=True, null=True, verbose_name='夹')),
                ('piece', models.SmallIntegerField(blank=True, null=True, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('uom', models.CharField(max_length=10, verbose_name='单位')),
                ('stock_trace', models.CharField(max_length=10, verbose_name='事务')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_stock_trace', to='product.Block', verbose_name='编号')),
            ],
            options={
                'verbose_name': '旧数据库存事务',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('reserve_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预留数量')),
                ('reserve_piece', models.IntegerField(default=0, verbose_name='预留件')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], max_length=6, verbose_name='单位')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('main_long', models.SmallIntegerField(blank=True, null=True, verbose_name='长')),
                ('main_height', models.SmallIntegerField(blank=True, null=True, verbose_name='高')),
                ('main_width', models.SmallIntegerField(blank=True, null=True, verbose_name='宽')),
                ('location', models.ForeignKey(limit_choices_to={'is_virtual': False}, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock.Location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.Product')),
            ],
            options={
                'verbose_name': '库存',
            },
        ),
        migrations.CreateModel(
            name='StockTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_stock_trace', to='contenttypes.ContentType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_trace_from', to='stock.Location', verbose_name='库位')),
                ('location_dest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stock_trace_to', to='stock.Location', verbose_name='目标库位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_trace', to='product.Product')),
            ],
            options={
                'verbose_name': '库存轨迹',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='仓库名称')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='缩写名称')),
                ('is_activate', models.BooleanField(default=True, verbose_name='启用')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_production', models.BooleanField(default=False, verbose_name='有生产活动')),
                ('_address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('partner', models.ForeignKey(blank=True, limit_choices_to={'type__in': ('production', 'supplier')}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='partner.Partner', verbose_name='合作伙伴')),
            ],
            options={
                'verbose_name': '仓库信息',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='stock.Warehouse', verbose_name='所属仓库'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('product', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'name')},
        ),
    ]
