# Generated by Django 2.1.2 on 2018-10-30 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchase.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0002_auto_20181029_1356'),
        ('product', '0003_auto_20181029_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('cancel', '取消')], max_length=20, verbose_name='状态')),
                ('order', models.CharField(db_index=True, default='New', max_length=26, unique=True, verbose_name='订单号码')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('currency', models.CharField(choices=[('USD', '$美元'), ('CNY', '￥人民币'), ('EUR', '€欧元')], max_length=10, verbose_name='货币')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], max_length=10, verbose_name='计量单位')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴')),
            ],
            options={
                'verbose_name': '采购订单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', purchase.fields.LineField(blank=True, verbose_name='行')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], max_length=10, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量')),
                ('long', models.IntegerField(null=True, verbose_name='长')),
                ('width', models.IntegerField(null=True, verbose_name='宽')),
                ('high', models.IntegerField(null=True, verbose_name='高')),
                ('m3', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='立方')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Block', verbose_name='荒料')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.PurchaseOrder', verbose_name='订单')),
            ],
            options={
                'verbose_name': '采购订单行',
                'ordering': ['order', 'line'],
            },
        ),
    ]
