# Generated by Django 2.1.2 on 2018-10-30 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', public.fields.LineField(blank=True, verbose_name='行')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], max_length=10, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量')),
                ('long', models.IntegerField(null=True, verbose_name='长')),
                ('width', models.IntegerField(null=True, verbose_name='宽')),
                ('high', models.IntegerField(null=True, verbose_name='高')),
                ('m3', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='立方')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importblock_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
        ),
    ]
