# Generated by Django 2.1.2 on 2018-10-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_importblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importblock',
            name='line',
        ),
        migrations.RemoveField(
            model_name='importblock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='importblock',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='编号'),
            preserve_default=False,
        ),
    ]
