# Generated by Django 2.1.2 on 2018-10-30 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20181030_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importblock',
            old_name='high',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='high',
            new_name='height',
        ),
    ]
