# Generated by Django 2.1.2 on 2018-10-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20181030_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importblock',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='importblock',
            name='long',
            field=models.IntegerField(blank=True, null=True, verbose_name='长'),
        ),
        migrations.AlterField(
            model_name='importblock',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方'),
        ),
        migrations.AlterField(
            model_name='importblock',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽'),
        ),
    ]
