# Generated by Django 2.1.2 on 2018-10-31 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0005_auto_20181030_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='uom',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseorderitem_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='name',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='long',
            field=models.IntegerField(blank=True, null=True, verbose_name='长'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽'),
        ),
    ]
