# Generated by Django 2.1.2 on 2018-10-31 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_auto_20181031_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.PurchaseOrder', verbose_name='订单'),
        ),
    ]
