# Generated by Django 2.1.2 on 2018-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_auto_20181031_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
    ]
