# Generated by Django 2.1.2 on 2018-10-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_purchaseorderitem_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['order'], 'verbose_name': '采购订单行'},
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='line',
        ),
    ]
