# Generated by Django 2.1.2 on 2018-10-31 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_auto_20181031_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='P',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('sex', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='D',
            fields=[
                ('p_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.P')),
                ('address', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
            ],
            bases=('purchase.p',),
        ),
    ]
