# Generated by Django 2.1.2 on 2018-10-31 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_d_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='E',
            fields=[
                ('p_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.P')),
                ('m2', models.IntegerField()),
            ],
            bases=('purchase.p',),
        ),
    ]
