# Generated by Django 2.1.2 on 2018-10-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_e'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d',
            name='p_ptr',
        ),
        migrations.RemoveField(
            model_name='e',
            name='p_ptr',
        ),
        migrations.DeleteModel(
            name='D',
        ),
        migrations.DeleteModel(
            name='E',
        ),
        migrations.DeleteModel(
            name='P',
        ),
    ]
