# Generated by Django 2.1.2 on 2018-10-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20181031_1419'),
        ('purchase', '0013_auto_20181031_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='block',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='height',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='long',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='m3',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='width',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='block_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.Block'),
            preserve_default=False,
        ),
    ]
