# Generated by Django 2.1.2 on 2018-11-01 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20181101_0453'),
        ('purchase', '0014_auto_20181031_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importblock',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='block_ptr',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='long',
            field=models.IntegerField(blank=True, null=True, verbose_name='长'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='type',
            field=models.CharField(default='block', max_length=10, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='重量'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽'),
        ),
        migrations.DeleteModel(
            name='ImportBlock',
        ),
    ]
