# Generated by Django 2.1.2 on 2018-11-01 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_auto_20181101_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='entry',
        ),
    ]
