# Generated by Django 2.1.2 on 2018-11-01 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchase', '0016_remove_purchaseorderitem_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseorderitem_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
    ]
