# Generated by Django 2.1.2 on 2018-11-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0017_purchaseorderitem_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='block_uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='荒料计量单位'),
        ),
    ]
