# Generated by Django 2.1.2 on 2018-11-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0018_purchaseorderitem_block_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='block_uom',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
    ]
