# Generated by Django 2.1.2 on 2018-11-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0020_auto_20181101_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order',
            field=models.CharField(max_length=20),
        ),
    ]
