# Generated by Django 2.1.2 on 2018-12-03 06:46

from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0024_purchaseorderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='entry',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='piece',
            field=models.IntegerField(default=1, verbose_name='件'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_production': False, 'type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.PurchaseOrder', verbose_name='订单'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='重量'),
        ),
    ]
