# Generated by Django 2.1.2 on 2018-12-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0025_auto_20181203_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='name',
            field=models.CharField(max_length=20, verbose_name='编号'),
        ),
    ]
