# Generated by Django 2.1.2 on 2018-12-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_packagelist_return_path'),
        ('purchase', '0026_auto_20181230_0650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('order', 'name', 'product'), ('order', 'name')},
        ),
    ]
