# Generated by Django 2.1.2 on 2019-01-03 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_invoicepartner'),
        ('purchase', '0028_auto_20190103_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.Supplier', verbose_name='供应商'),
        ),
    ]
