# Generated by Django 2.1.2 on 2019-01-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_auto_20190103_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='batch',
            field=models.CharField(blank=True, help_text='如果不填，则采取"-"号前或编号前2位作为批次号', max_length=10, null=True, verbose_name='批次'),
        ),
    ]
