# Generated by Django 2.1.2 on 2019-01-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0030_auto_20190103_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='purchase.Supplier', verbose_name='供应商'),
            preserve_default=False,
        ),
    ]
