# Generated by Django 2.1.2 on 2019-01-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0032_auto_20190108_0700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='partner.Supplier', verbose_name='供应商'),
        ),
    ]
