# Generated by Django 2.1.2 on 2019-02-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0033_auto_20190115_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['line'], 'verbose_name': '采购订单行'},
        ),
    ]
