# Generated by Django 2.1.2 on 2018-11-05 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0003_auto_20181030_0557'),
        ('product', '0013_auto_20181105_0640'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockCheckInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', public.fields.OrderField(blank=True, max_length=20, verbose_name='单号')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockcheckinorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockcheckinorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴')),
            ],
            options={
                'verbose_name': '荒料到货入库单',
            },
        ),
        migrations.CreateModel(
            name='BlockCheckInOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.BlockCheckInOrder', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '荒料到货入库单明细项',
            },
        ),
    ]
