# Generated by Django 2.1.2 on 2018-11-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0022_auto_20181102_0507'),
        ('mrp', '0002_auto_20181105_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='object_id',
        ),
        migrations.AddField(
            model_name='blockcheckinorder',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block_check_in_order', to='purchase.PurchaseOrder', verbose_name='采购订单'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blockcheckinorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrp.BlockCheckInOrder', verbose_name='items'),
        ),
    ]
