# Generated by Django 2.1.2 on 2018-11-06 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20181106_0611'),
        ('mrp', '0005_auto_20181106_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcheckinorder',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='卸货仓库'),
            preserve_default=False,
        ),
    ]
