# Generated by Django 2.1.2 on 2018-11-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20181106_0929'),
        ('mrp', '0006_blockcheckinorder_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcheckinorder',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockcheckinorder_location_from', to='stock.Location', verbose_name='原库位'),
        ),
        migrations.AddField(
            model_name='blockcheckinorder',
            name='location_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockcheckinorder_location_to', to='stock.Location', verbose_name='目标库位'),
        ),
    ]
