# Generated by Django 2.1.2 on 2018-11-09 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import purchase.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0003_auto_20181030_0557'),
        ('stock', '0009_auto_20181107_1219'),
        ('product', '0013_auto_20181105_0640'),
        ('mrp', '0007_auto_20181107_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='KesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', purchase.fields.OrderField(blank=True, default='New', max_length=20, verbose_name='单号')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kesorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kesorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kesorder_location_from', to='stock.Location', verbose_name='原库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kesorder_location_to', to='stock.Location', verbose_name='目标库位')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴')),
            ],
            options={
                'verbose_name': '界石加工单',
            },
        ),
        migrations.CreateModel(
            name='KesOrderProduceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='计量单位')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='厚度规格')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produce_items', to='mrp.KesOrder', verbose_name='对应界石单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '界石单毛板项',
            },
        ),
        migrations.CreateModel(
            name='KesOrderRawItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.KesOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '界石单荒料项',
            },
        ),
        migrations.AddField(
            model_name='kesorderproduceitem',
            name='raw_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='mrp.KesOrderRawItem', verbose_name='原材料'),
        ),
    ]
