# Generated by Django 2.1.2 on 2018-11-09 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0008_auto_20181109_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='kesorderrawitem',
            name='m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='立方数'),
        ),
    ]
