# Generated by Django 2.1.2 on 2018-11-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0009_kesorderrawitem_m3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kesorderproduceitem',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='厚度规格'),
        ),
    ]
