# Generated by Django 2.1.2 on 2018-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0011_auto_20181125_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcheckinorder',
            name='state',
            field=models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='kesorder',
            name='state',
            field=models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
