# Generated by Django 2.1.2 on 2018-11-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20181126_0237'),
        ('stock', '0011_auto_20181125_0939'),
        ('partner', '0004_auto_20181125_0544'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0012_auto_20181125_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveLocationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态')),
                ('order', public.fields.OrderField(db_index=True, default='New', max_length=26, unique=True, verbose_name='订单号码')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movelocationorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movelocationorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movelocationorder_location', to='stock.Location', verbose_name='原库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movelocationorder_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_out_warehouse', to='stock.Warehouse', verbose_name='移出仓库')),
                ('warehouse_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_in_warehouse', to='stock.Warehouse', verbose_name='接收仓库')),
            ],
            options={
                'verbose_name': '移库单',
            },
        ),
        migrations.CreateModel(
            name='MoveLocationOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方')], default='t', max_length=10, verbose_name='计量单位')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movelocationorderitem_location', to='stock.Location', verbose_name='库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='movelocationorderitem_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='码单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '移库单明细行',
            },
        ),
    ]
