# Generated by Django 2.1.2 on 2018-11-26 08:41

from django.db import migrations
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0013_movelocationorder_movelocationorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movelocationorder',
            name='order',
            field=public.fields.OrderField(blank=True, default='New', max_length=20, verbose_name='单号'),
        ),
    ]
