# Generated by Django 2.1.2 on 2018-11-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0014_auto_20181126_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='movelocationorderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.MoveLocationOrder', verbose_name='对应移库单'),
        ),
    ]
