# Generated by Django 2.1.2 on 2018-11-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0015_movelocationorderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcheckinorderitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
        migrations.AlterField(
            model_name='kesorderproduceitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
        migrations.AlterField(
            model_name='kesorderrawitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
        migrations.AlterField(
            model_name='movelocationorderitem',
            name='uom',
            field=models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位'),
        ),
    ]
