# Generated by Django 2.1.2 on 2018-11-28 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20181128_1447'),
        ('partner', '0004_auto_20181125_0544'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0012_auto_20181126_1554'),
        ('mrp', '0017_auto_20181126_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlabCheckInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', public.fields.OrderField(blank=True, default='New', max_length=20, verbose_name='单号')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabcheckinorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabcheckinorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slabcheckinorder_location', to='stock.Location', verbose_name='原库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slabcheckinorder_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '板材入库单',
            },
        ),
        migrations.CreateModel(
            name='SlabCheckInOrderProduceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位')),
                ('price', models.DecimalField(decimal_places=2, help_text='平方单价', max_digits=8, verbose_name='单价')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slabcheckinorderitem_location', to='stock.Location', verbose_name='库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slabcheckinorderitem_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.SlabCheckInOrder', verbose_name='板材入库单')),
                ('package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='码单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '板材入库单明细行',
            },
        ),
        migrations.AlterModelOptions(
            name='blockcheckinorderitem',
            options={'verbose_name': '荒料到货入库单明细行'},
        ),
        migrations.AlterModelOptions(
            name='kesorderproduceitem',
            options={'verbose_name': '界石单毛板行'},
        ),
        migrations.AlterModelOptions(
            name='kesorderrawitem',
            options={'verbose_name': '界石单荒料行'},
        ),
        migrations.AlterField(
            model_name='movelocationorder',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='账单[对方]对应本项。如果为空，则不会生产账单', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='运输单位'),
        ),
    ]
