# Generated by Django 2.1.2 on 2018-11-30 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20181129_2325'),
        ('partner', '0004_auto_20181125_0544'),
        ('stock', '0012_auto_20181126_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0018_auto_20181128_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', public.fields.OrderField(blank=True, default='New', max_length=20, verbose_name='单号')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productionorder_location', to='stock.Location', verbose_name='原库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productionorder_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴')),
            ],
            options={
                'verbose_name': '生产订单',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderProduceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位')),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='厚度规格')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='立方单价', max_digits=8, null=True, verbose_name='单价')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productionorderproduceitem_location', to='stock.Location', verbose_name='库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productionorderproduceitem_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_items', to='mrp.ProductionOrder', verbose_name='对应界石单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '生产单成品行',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderRawItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece', models.IntegerField(default=1, verbose_name='件')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='单价')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='数量')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productionorderrawitem_location', to='stock.Location', verbose_name='库位')),
                ('location_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='productionorderrawitem_location_dest', to='stock.Location', verbose_name='目标库位')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.ProductionOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': '生产单原料行',
            },
        ),
        migrations.CreateModel(
            name='ProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='业务类型')),
                ('expense_by', models.CharField(choices=[('raw', '原材料项'), ('produce', '产品项'), ('all', '原料及产品')], max_length=10, verbose_name='费用结算按')),
                ('raw_item_type', models.CharField(choices=[('block', '荒料'), ('semi_slab', '毛板'), ('slab', '板材')], default='block', max_length=10, verbose_name='原材料类型')),
                ('produce_item_type', models.CharField(choices=[('block', '荒料'), ('semi_slab', '毛板'), ('slab', '板材')], default='block', max_length=10, verbose_name='产出品类型')),
                ('activate', models.BooleanField(default=False, verbose_name='启用')),
            ],
            options={
                'verbose_name': '生产业务类型明细',
            },
        ),
        migrations.RemoveField(
            model_name='slabcheckinorder',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='slabcheckinorder',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='slabcheckinorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='slabcheckinorder',
            name='location_dest',
        ),
        migrations.RemoveField(
            model_name='slabcheckinorder',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='slabcheckinorder',
            name='warehouse',
        ),

        migrations.AlterModelOptions(
            name='kesorder',
            options={'verbose_name': '生产加工单'},
        ),
        migrations.DeleteModel(
            name='SlabCheckInOrder',
        ),


        migrations.AddField(
            model_name='productionorder',
            name='production_type',
            field=models.ForeignKey(limit_choices_to={'activate': True}, on_delete=django.db.models.deletion.CASCADE, to='mrp.ProductionType', verbose_name='业务类型'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='仓库'),
        ),
    ]
