# Generated by Django 2.1.2 on 2018-11-30 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0019_auto_20181130_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderproduceitem',
            name='raw_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produces', to='mrp.ProductionOrderRawItem', verbose_name='原材料'),
            preserve_default=False,
        ),
    ]
