# Generated by Django 2.1.2 on 2018-11-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0020_productionorderproduceitem_raw_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderproduceitem',
            name='raw_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.ProductionOrderRawItem', verbose_name='原材料'),
        ),
    ]
