# Generated by Django 2.1.2 on 2018-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0022_auto_20181130_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorderrawitem',
            name='piece',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='件'),
        ),
    ]
