# Generated by Django 2.1.2 on 2018-12-02 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_semi_slab_single_qty'),
        ('mrp', '0023_auto_20181202_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderproduceitem',
            name='draft_package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.DraftPackageList', verbose_name='草稿码单'),
        ),
        migrations.AddField(
            model_name='productionorderproduceitem',
            name='package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='码单'),
        ),
    ]
