# Generated by Django 2.1.2 on 2018-12-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0024_auto_20181202_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kesorder',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='kesorder',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='kesorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='kesorder',
            name='location_dest',
        ),
        migrations.RemoveField(
            model_name='kesorder',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='kesorder',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='kesorderproduceitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='kesorderproduceitem',
            name='location_dest',
        ),
        migrations.RemoveField(
            model_name='kesorderproduceitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='kesorderproduceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='kesorderproduceitem',
            name='raw_item',
        ),
        migrations.RemoveField(
            model_name='kesorderrawitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='kesorderrawitem',
            name='location_dest',
        ),
        migrations.RemoveField(
            model_name='kesorderrawitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='kesorderrawitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='KesOrder',
        ),
        migrations.DeleteModel(
            name='KesOrderProduceItem',
        ),
        migrations.DeleteModel(
            name='KesOrderRawItem',
        ),
    ]
