# Generated by Django 2.1.2 on 2018-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0026_auto_20181207_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutorder',
            name='cart_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='车牌/柜号'),
        ),
        migrations.AddField(
            model_name='inoutorder',
            name='pickup_staff',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='提货人'),
        ),
    ]
