# Generated by Django 2.1.2 on 2018-12-07 08:52

from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0027_auto_20181207_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockcheckinorderitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inoutorderitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movelocationorderitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionorderproduceitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionorderrawitem',
            name='line',
            field=public.fields.LineField(blank=True, default=1, verbose_name='行'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionorderproduceitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce_items', to='mrp.ProductionOrder', verbose_name='对应生产单'),
        ),
        migrations.AlterField(
            model_name='productionorderproduceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='单价'),
        ),
    ]
