# Generated by Django 2.1.2 on 2018-12-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0028_auto_20181207_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='location',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='location_dest',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorder',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorderitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorderitem',
            name='location_dest',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='blockcheckinorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='BlockCheckInOrder',
        ),
        migrations.DeleteModel(
            name='BlockCheckInOrderItem',
        ),
    ]
