# Generated by Django 2.1.2 on 2018-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0029_auto_20181208_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_production': True, 'type': 'supplier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='业务伙伴'),
        ),
    ]
