# Generated by Django 2.1.2 on 2018-12-14 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0032_turnbackorder_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnbackorder',
            options={'verbose_name': '库存回退'},
        ),
        migrations.AlterModelOptions(
            name='turnbackorderitem',
            options={'verbose_name': '库存回退明细行'},
        ),
    ]
