# Generated by Django 2.1.2 on 2018-12-14 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0034_auto_20181214_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inoutorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='movelocationorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='productionorderrawitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品'),
        ),
        migrations.AlterField(
            model_name='turnbackorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品'),
        ),
    ]
