# Generated by Django 2.1.2 on 2018-12-15 12:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20181212_0305'),
        ('product', '0032_auto_20181212_0152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0035_auto_20181214_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='盘点简述')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('done', '完成'), ('cancel', '取消')], default='draft', max_length=20, verbose_name='状态')),
                ('order', public.fields.OrderField(blank=True, default='New', max_length=20, verbose_name='单号')),
                ('type', models.CharField(blank=True, choices=[('block', '荒料'), ('semi_slab', '毛板'), ('slab', '板材')], max_length=10, null=True, verbose_name='产品类型')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryorder_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('warehouse', models.ForeignKey(blank=True, help_text='盘点的仓库', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='接收仓库')),
            ],
            options={
                'verbose_name': '盘点库存',
            },
        ),
        migrations.CreateModel(
            name='InventoryOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', public.fields.LineField(blank=True, verbose_name='行')),
                ('old_piece', models.IntegerField(default=1, verbose_name='原件数')),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原数量')),
                ('piece', models.IntegerField(default=1, verbose_name='实际件数')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位')),
                ('draft_package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.DraftPackageList', verbose_name='草稿码单')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_location', to='stock.Location', verbose_name='实际库位')),
                ('old_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_old_location', to='stock.Location', verbose_name='原库位')),
                ('old_package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryorderitem_old_package_list', to='product.PackageList', verbose_name='码单')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mrp.InventoryOrder', verbose_name='对应订单')),
                ('package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='码单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '盘点库存明细行',
            },
        ),
    ]
