# Generated by Django 2.1.2 on 2018-12-15 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0036_inventoryorder_inventoryorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryorder',
            old_name='type',
            new_name='product_type',
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryorderitem_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='is_equal',
            field=models.BooleanField(default=False, verbose_name='相符'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='ps',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='备注'),
        ),
        migrations.RemoveField(
            model_name='inventoryorder',
            name='handler',
        ),
        migrations.AddField(
            model_name='inventoryorder',
            name='handler',
            field=models.ManyToManyField(related_name='inventoryorder_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人'),
        ),
    ]
