# Generated by Django 2.1.2 on 2018-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0037_auto_20181215_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorderitem',
            name='is_equal',
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='完成'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='is_lose',
            field=models.BooleanField(default=False, help_text='已不在库的', verbose_name='丢失'),
        ),
    ]
