# Generated by Django 2.1.2 on 2018-12-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0039_auto_20181215_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际件数'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际数量'),
        ),
    ]
