# Generated by Django 2.1.2 on 2018-12-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0040_auto_20181215_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorderitem',
            name='is_equal',
            field=models.BooleanField(default=False, verbose_name='与原数据相符'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='location',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_location', to='stock.Location', verbose_name='实际库位'),
        ),
    ]
