# Generated by Django 2.1.2 on 2018-12-16 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20181212_0152'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrp', '0041_auto_20181215_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrderNewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', public.fields.LineField(blank=True, verbose_name='行')),
                ('name', models.CharField(max_length=20, verbose_name='产品编号')),
                ('product_type', models.CharField(choices=[('block', '荒料'), ('semi_slab', '毛板'), ('slab', '板材')], max_length=10, verbose_name='产品类型')),
                ('piece', models.IntegerField(blank=True, null=True, verbose_name='实际件数')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际数量')),
                ('uom', models.CharField(choices=[('t', '吨'), ('m3', '立方'), ('m2', '平方')], default='t', max_length=10, verbose_name='计量单位')),
                ('ps', models.CharField(blank=True, max_length=120, null=True, verbose_name='备注')),
                ('draft_package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.DraftPackageList', verbose_name='草稿码单')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryordernewitem_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_items', to='mrp.InventoryOrder', verbose_name='对应订单')),
                ('package_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='码单')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '盘点新增产品',
            },
        ),
    ]
