# Generated by Django 2.1.2 on 2018-12-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20181212_0305'),
        ('mrp', '0042_inventoryordernewitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryordernewitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryordernewitem_location', to='stock.Location', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='inventoryordernewitem',
            name='location_dest',
            field=models.ForeignKey(default=1, limit_choices_to={'is_virtual': False}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryordernewitem_location_dest', to='stock.Location', verbose_name='实际库位'),
            preserve_default=False,
        ),
    ]
