# Generated by Django 2.1.2 on 2018-12-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0043_auto_20181216_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryorder',
            options={'ordering': ('-created',), 'verbose_name': '盘点库存'},
        ),
        migrations.AlterModelOptions(
            name='inventoryorderitem',
            options={'ordering': ('line',), 'verbose_name': '盘点库存明细行'},
        ),
        migrations.AlterModelOptions(
            name='inventoryordernewitem',
            options={'ordering': ('line',), 'verbose_name': '盘点新增产品'},
        ),
        migrations.RemoveField(
            model_name='inventoryorderitem',
            name='is_done',
        ),
    ]
