# Generated by Django 2.1.2 on 2018-12-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0044_auto_20181216_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorderitem',
            name='is_equal',
        ),
        migrations.RemoveField(
            model_name='inventoryorderitem',
            name='is_lose',
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='report',
            field=models.CharField(choices=[('is_equal', '与原数据相符'), ('is_lose', '丢失,已不在库的'), ('not_equal', '数据不符(下方输入数据)')], default=1, max_length=10, verbose_name='情况报告'),
            preserve_default=False,
        ),
    ]
