# Generated by Django 2.1.2 on 2018-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0045_auto_20181216_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='report',
            field=models.CharField(choices=[(None, '未盘点'), ('is_equal', '与原数据相符'), ('is_lose', '丢失,已不在库的'), ('not_equal', '数据不符(下方输入数据)')], max_length=10, verbose_name='情况报告'),
        ),
    ]
