# Generated by Django 2.1.2 on 2018-12-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_auto_20181212_0305'),
        ('product', '0035_auto_20181217_1108'),
        ('mrp', '0051_auto_20181217_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorderitem',
            name='now_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_now_location', to='stock.Location', verbose_name='现库位'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='now_package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryorderitem_now_package_list', to='product.PackageList', verbose_name='现码单'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='now_piece',
            field=models.IntegerField(default=1, verbose_name='现件数'),
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='now_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='现数量'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='old_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_old_location', to='stock.Location', verbose_name='原库位'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_location', to='stock.Location', verbose_name='库位'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='location_dest',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_virtual': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventoryorderitem_dest_location', to='stock.Location', verbose_name='目标库位'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='old_package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryorderitem_old_package_list', to='product.PackageList', verbose_name='原库码单'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='件数'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量'),
        ),
    ]
