# Generated by Django 2.1.2 on 2018-12-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0052_auto_20181217_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='now_piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='现件数'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitem',
            name='now_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='现数量'),
        ),
    ]
