# Generated by Django 2.1.2 on 2018-12-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20181217_1108'),
        ('mrp', '0054_inventoryordernewitem_thickness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryordernewitem',
            name='name',
        ),
        migrations.AddField(
            model_name='inventoryordernewitem',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Block', verbose_name='荒料编号'),
        ),
    ]
