# Generated by Django 2.1.2 on 2018-12-20 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_auto_20181219_0249'),
        ('purchase', '0025_auto_20181203_0646'),
        ('mrp', '0055_auto_20181218_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='inoutorderitem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_out_order_items', to='purchase.PurchaseOrderItem', verbose_name='采购订单明细行'),
        ),
        migrations.AddField(
            model_name='inoutorderitem',
            name='sales_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_out_order_items', to='sales.SalesOrderItem', verbose_name='销售订单明细行'),
        ),
    ]
