# Generated by Django 2.1.2 on 2018-12-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_packagelist_return_path'),
        ('mrp', '0056_auto_20181220_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderrawitem',
            name='package_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.PackageList', verbose_name='码单'),
        ),
    ]
