# Generated by Django 2.1.2 on 2019-01-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0057_productionorderrawitem_package_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ('-date',), 'verbose_name': '生产订单'},
        ),
    ]
