# Generated by Django 2.1.2 on 2019-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0057_productionorderrawitem_package_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ('-date',), 'verbose_name': '生产订单'},
        ),
        migrations.AlterField(
            model_name='productiontype',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
    ]
