# Generated by Django 2.1.2 on 2019-01-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_invoicepartner'),
        ('mrp', '0058_auto_20190102_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrpSupplier',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
    ]
