# Generated by Django 2.1.2 on 2019-01-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0061_auto_20190108_0654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MrpSupplier',
        ),
    ]
