# Generated by Django 2.1.2 on 2019-01-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0020_delete_mrpsupplier'),
        ('mrp', '0062_delete_mrpsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrpSupplier',
            fields=[
            ],
            options={
                'verbose_name': '生产/服务商资料',
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
    ]
