# Generated by Django 2.1.2 on 2019-01-15 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0063_mrpsupplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MrpSupplier',
        ),
    ]
