# Generated by Django 2.1.2 on 2019-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0065_auto_20190116_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderproduceitem',
            name='pi',
            field=models.IntegerField(blank=True, null=True, verbose_name='皮'),
        ),
        migrations.AddField(
            model_name='productionorderproduceitem',
            name='pic',
            field=models.IntegerField(blank=True, null=True, verbose_name='件'),
        ),
    ]
