# Generated by Django 2.1.2 on 2019-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0066_auto_20190118_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='expense_by_uom',
            field=models.CharField(choices=[('part', '夹数'), ('quantity', '数量(t/m3/m2)'), ('one', '次/个/车'), ('another', '手动输入数量')], max_length=20, verbose_name='计费单位'),
        ),
    ]
