# Generated by Django 2.1.2 on 2019-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0067_auto_20190119_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量'),
        ),
    ]
