# Generated by Django 2.1.2 on 2019-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0068_auto_20190119_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryorderitem',
            name='now_location',
        ),
        migrations.RemoveField(
            model_name='inventoryorderitem',
            name='report',
        ),
        migrations.AddField(
            model_name='inventoryorderitem',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='已盘'),
        ),
    ]
