# Generated by Django 2.1.2 on 2018-11-02 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import public.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('partner', '0003_auto_20181030_0557'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activate', models.BooleanField(default=True, verbose_name='启用')),
                ('name', models.CharField(max_length=20, verbose_name='帐户名称')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登记')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('confirm', '确认'), ('cancel', '取消')], default='draft', max_length=10, verbose_name='状态')),
                ('order', public.fields.OrderField(db_index=True, default='New', max_length=26, verbose_name='订单号码')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('object_id', models.PositiveIntegerField()),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_partner', to='partner.Partner', verbose_name='对方')),
            ],
            options={
                'verbose_name': '账单',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='项目')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.Invoice', verbose_name='账单')),
            ],
            options={
                'verbose_name': '账单项',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Account', verbose_name='帐户')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_partner', to=settings.AUTH_USER_MODEL, verbose_name='对方')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payments',
            field=models.ManyToManyField(related_name='assign_invoices', through='invoice.Assign', to='invoice.Payment'),
        ),
        migrations.AddField(
            model_name='assign',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice', verbose_name='账单'),
        ),
        migrations.AddField(
            model_name='assign',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Payment', verbose_name='款项'),
        ),
    ]
