# Generated by Django 2.1.2 on 2018-12-24 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_auto_20181224_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceduedatedefaultset',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('salesorder', 'purchaseorder', 'movelocationorder', 'productionorder', 'inoutorder', 'inventoryorder')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', unique=True, verbose_name='对应order'),
        ),
    ]
