# Generated by Django 2.1.2 on 2018-12-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoice', '0019_auto_20181226_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
