# Generated by Django 2.1.2 on 2018-12-30 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_auto_20181229_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ('line',), 'verbose_name': '账单项'},
        ),
    ]
