# Generated by Django 2.1.2 on 2019-03-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('city', models.IntegerField(verbose_name='对应市id')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'ordering': ('city', 'id'),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('code', models.IntegerField(verbose_name='对应省份id')),
            ],
            options={
                'verbose_name': '城市列表',
                'verbose_name_plural': '城市列表',
                'ordering': ('code', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo', verbose_name='logo')),
                ('address_detail', models.TextField(verbose_name='详细地址')),
            ],
            options={
                'verbose_name': '公司资料',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('is_company', models.BooleanField(default=False, verbose_name='公司')),
                ('type', models.CharField(choices=[('customer', '客户'), ('supplier', '供应商'), ('production', '生产商'), ('service', '运输/服务商'), ('invoice', '账单费用')], default='customer', max_length=20, verbose_name='伙伴类型')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('sex', models.CharField(blank=True, choices=[('male', '先生'), ('female', '女士')], max_length=10, null=True, verbose_name='性别')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_activate', models.BooleanField(default=True, verbose_name='启用')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.City', verbose_name='城市')),
                ('company', models.ForeignKey(blank=True, limit_choices_to={'is_company': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='partner.Partner', verbose_name='所属公司')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '伙伴资料',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('code', models.IntegerField(help_text='用于与市级联动', primary_key=True, serialize=False, verbose_name='省份id')),
            ],
            options={
                'verbose_name': '省份列表',
                'verbose_name_plural': '省份列表',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Province', verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='公司资料'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': '客户',
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
        migrations.CreateModel(
            name='InvoicePartner',
            fields=[
            ],
            options={
                'verbose_name': '账单账号',
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
        migrations.CreateModel(
            name='MrpSupplier',
            fields=[
            ],
            options={
                'verbose_name': '生产/服务商资料',
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
            ],
            options={
                'verbose_name': '供应商',
                'proxy': True,
                'indexes': [],
            },
            bases=('partner.partner',),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('phone', 'name', 'province', 'city')},
        ),
    ]
