# Generated by Django 2.1.7 on 2019-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190319_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-time', '-updated', '-created'], 'verbose_name': '提醒事项'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=100, verbose_name='提醒标题'),
        ),
    ]
