# Generated by Django 2.1.7 on 2019-03-25 05:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None, verbose_name='编号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collect_block', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户收集荒料编号',
            },
        ),
    ]
