# Generated by Django 2.1.2 on 2018-12-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20181214_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlogs',
            name='change_data',
        ),
    ]
