# Generated by Django 2.1.7 on 2019-03-19 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeWxPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('title', models.CharField(max_length=80, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='内容')),
                ('url', models.URLField(blank=True, null=True, verbose_name='链接')),
                ('app_name', models.CharField(max_length=200, verbose_name='推送app')),
                ('user_ids', models.TextField(default='@all', verbose_name='推送用户')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': '计划微信推送',
            },
        ),
    ]
