# Generated by Django 2.1.2 on 2019-01-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_wxconfig_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxconfig',
            name='app_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
