# Generated by Django 2.1.2 on 2019-03-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.FileField(upload_to=files.models.get_upload_to)),
                ('desc', models.CharField(blank=True, max_length=120, null=True, verbose_name='简述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
            ],
            options={
                'verbose_name': '文件',
                'ordering': ['-created'],
            },
        ),
    ]
