# Generated by Django 2.1.2 on 2019-01-03 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
            preserve_default=False,
        ),
    ]
