# Generated by Django 2.1.7 on 2019-03-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created',), 'permissions': (('can_draft', '设为草稿'), ('can_cancel', '设为取消')), 'verbose_name': '账单'},
        ),
    ]
