# Generated by Django 2.1.7 on 2019-03-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20190313_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceduedatedefaultset',
            name='content_type',
            field=models.OneToOneField(limit_choices_to={'model__in': ('salesorder', 'purchaseorder', 'movelocationorder', 'productionorder', 'inoutorder', 'inventoryorder')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='对应order'),
        ),
    ]
