# Generated by Django 2.1.2 on 2018-12-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_operationlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlogs',
            name='type',
            field=models.CharField(choices=[('new', '创建'), ('update', '更新')], max_length=10, verbose_name='类型'),
        ),
    ]
