# Generated by Django 2.1.2 on 2018-12-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_operationlogs_change_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationlogs',
            name='type',
        ),
    ]
