# Generated by Django 2.1.2 on 2018-12-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_remove_operationlogs_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
