# Generated by Django 2.1.2 on 2019-03-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20190220_0559'),
        ('files', '0003_auto_20190220_0558'),
    ]

    operations = [
    ]
