# Generated by Django 2.1.2 on 2018-12-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20181214_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('-1', '支付'), ('1', '收款')], default='-1', max_length=2, verbose_name='支付/收款'),
        ),
    ]
