# Generated by Django 2.1.2 on 2018-12-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_auto_20181222_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='确认款项'),
        ),
    ]
