# Generated by Django 2.1.2 on 2018-12-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_payment_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('-1', '付款'), ('1', '收款')], default='-1', max_length=2, verbose_name='付款/收款'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('-1', '付款'), ('1', '收款')], default='-1', max_length=2, verbose_name='支付/收款'),
        ),
    ]
