# Generated by Django 2.1.2 on 2018-12-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoice', '0014_auto_20181222_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDueDateDefaultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.CharField(choices=[('0', '立刻'), ('7', '7天后'), ('15', '15天后'), ('30', '30天后'), ('end_of_month', '月底'), ('end_of_year', '年底')], max_length=20, verbose_name='默认值选项')),
                ('updated', models.DateField(auto_now=True, verbose_name='设置时间')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('salesorder', 'purchaseorder', 'movelocationorder', 'productionorder', 'inoutorder', 'inventoryorder')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='对应order')),
            ],
            options={
                'verbose_name': '账单限期默认设置',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created', 'confirm'), 'verbose_name': '收付款记录'},
        ),
    ]
