# Generated by Django 2.1.2 on 2018-12-26 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20181226_0333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
    ]
