#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by pbpoon on 2018/10/30
from django.urls import path
from . import views
urlpatterns = [
    path('expenses/', views.ExpensesInvoiceListView.as_view(), name='expenses_invoice_list'),
    path('purchase/', views.PurchaseInvoiceListView.as_view(), name='purchase_invoice_list'),
    path('sales/', views.SalesInvoiceListView.as_view(), name='sales_invoice_list'),
    path('<invoice_id>/payment/<partner_id>/', views.PaymentEditView.as_view(), name='payment_create_from_invoice'),
    # path('<invoice_id>/payment/<partner_id>/', views.PaymentEditView.as_view(), name='payment_create_from_invoice'),
    path('payment/<int:pk>/edit/', views.PaymentEditView.as_view(), name='payment_edit'),
    path('payment/<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment_delete'),
    path('payment/<int:pk>/', views.PaymentDetailView.as_view(), name='payment_detail'),
    path('payment/day-daily/', views.PaymentDayListView.as_view(), name='PaymentDayListView'),
    path('payment/', views.PaymentListView.as_view(), name='payment_list'),
    path('account/<int:pk>/update/', views.AccountUpdateView.as_view(), name='account_update'),
    path('account/create/', views.AccountCreateView.as_view(), name='account_create'),
    path('account/<int:pk>/', views.AccountDetailView.as_view(), name='account_detail'),
    path('account/', views.AccountListView.as_view(), name='account_list'),
    path('assign/<int:invoice_id>/<int:payment_id>', views.AssignPaymentFormView.as_view(), name='assign_payment'),
    path('assign/delete/<int:assign_id>', views.AssignDeleteView.as_view(), name='assign_delete'),
    path('item/create/<order_id>/', views.InvoiceItemEditView.as_view(), name='invoice_item_create'),
    path('item/delete/<int:pk>/', views.InvoiceItemDeleteView.as_view(), name='invoice_item_delete'),
    path('item/edit/<int:pk>/', views.InvoiceItemEditView.as_view(), name='invoice_item_edit'),
    path('<int:pk>/quick-assign-undercharge-payment/', views.QuickInvoiceAssignUnderchargePayment.as_view(),
         name='invoice_quick_assign_undercharge_payment'),
    path('invoice_due_date_default_update/<int:pk>/', views.InvoiceDueDateDefaultSetUpdateView.as_view(),
         name='invoice_due_date_default_update'),
    path('invoice_due_date_default_create/', views.InvoiceDueDateDefaultSetCreateView.as_view(),
         name='invoice_due_date_default_create'),
    path('invoice_due_date_default_list/', views.InvoiceDueDateDefaultSetListView.as_view(),
         name='invoice_due_date_default_list'),
    path('create/<app_label_lower>/<order_id>/', views.SalesInvoiceCreateView.as_view(), name='sales_invoice_create'),
    path('create/<app_label_lower>/<order_id>/', views.InvoiceCreateView.as_view(), name='invoice_create'),
    path('update/<int:pk>/', views.InvoiceUpdateView.as_view(), name='invoice_update'),
    path('purchase/<int:pk>/', views.PurchaseInvoiceDetailView.as_view(), name='purchase_invoice_detail'),
    path('expenses/<int:pk>/', views.ExpensesInvoiceDetailView.as_view(), name='expenses_invoice_detail'),
    path('sales/<int:pk>/', views.SalesInvoiceDetailView.as_view(), name='sales_invoice_detail'),
    path('<int:pk>/', views.InvoiceDetailView.as_view(), name='invoice_detail'),
    path('month/', views.InvoiceMonthListView.as_view(), name='invoice_month_list'),
    path('day-daily/', views.InvoiceDayListView.as_view(), name='invoice_day_daily_list'),
    path('', views.InvoiceListView.as_view(), name='invoice_list'),
]
