# Generated by Django 2.1.2 on 2018-10-29 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('father_id', models.SmallIntegerField(verbose_name='对应省份id')),
            ],
            options={
                'verbose_name': '城市列表',
                'verbose_name_plural': '城市列表',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('is_company', models.BooleanField(default=False, verbose_name='公司')),
                ('type', models.CharField(choices=[('customer', '客户'), ('supplier', '供应商'), ('employee', '员工')], default='customer', max_length=20, verbose_name='伙伴类型')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('sex', models.CharField(blank=True, choices=[('male', '先生'), ('female', '女士')], max_length=10, null=True, verbose_name='性别')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_activate', models.BooleanField(default=True, verbose_name='启用')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.City', verbose_name='城市')),
                ('entry_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_entry', to=settings.AUTH_USER_MODEL, verbose_name='数据登记')),
            ],
            options={
                'verbose_name': '伙伴资料',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('province_id', models.SmallIntegerField(help_text='用于与市级联动', verbose_name='省份id')),
            ],
            options={
                'verbose_name': '省份列表',
                'verbose_name_plural': '省份列表',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Province', verbose_name='省份'),
        ),
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('phone', 'name')},
        ),
    ]
