# Generated by Django 2.1.2 on 2018-11-25 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20181030_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_company': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='partner.Partner', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_production',
            field=models.BooleanField(default=False, verbose_name='是生产商'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('customer', '客户'), ('supplier', '供应商')], default='customer', max_length=20, verbose_name='伙伴类型'),
        ),
    ]
