# Generated by Django 2.1.2 on 2018-12-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20181125_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='father_id',
            new_name='code_id',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='province_id',
            new_name='code',
        ),
    ]
