# Generated by Django 2.1.2 on 2018-12-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181210_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='code_id',
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.IntegerField(default=1, verbose_name='对应省份id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.IntegerField(help_text='用于与市级联动', verbose_name='省份id'),
        ),
        migrations.AlterField(
            model_name='province',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
