# Generated by Django 2.1.2 on 2018-12-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('city', 'id'), 'verbose_name': '地区', 'verbose_name_plural': '地区'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('code', 'id'), 'verbose_name': '城市列表', 'verbose_name_plural': '城市列表'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('id',), 'verbose_name': '省份列表', 'verbose_name_plural': '省份列表'},
        ),
        migrations.AddField(
            model_name='partner',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Area', verbose_name='地区'),
        ),
    ]
