# Generated by Django 2.1.2 on 2018-12-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20181210_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ('code',), 'verbose_name': '省份列表', 'verbose_name_plural': '省份列表'},
        ),
        migrations.RemoveField(
            model_name='province',
            name='id',
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.IntegerField(help_text='用于与市级联动', primary_key=True, serialize=False, verbose_name='省份id'),
        ),
    ]
