# Generated by Django 2.1.2 on 2018-12-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_salesorder_area'),
        ('partner', '0009_auto_20181210_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
