# Generated by Django 2.1.2 on 2018-12-11 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20181211_0520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together=set(),
        ),
    ]
