# Generated by Django 2.1.2 on 2018-12-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20181211_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='公司资料')),
            ],
            options={
                'verbose_name': '公司资料',
            },
        ),
    ]
