# Generated by Django 2.1.2 on 2018-12-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0012_maininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_invoice',
            field=models.BooleanField(default=False, verbose_name='是账单账户类型'),
        ),
    ]
