# Generated by Django 2.1.2 on 2019-01-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_invoicepartner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='是运输/服务商'),
        ),
    ]
