# Generated by Django 2.1.2 on 2019-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_partner_is_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='is_invoice',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_production',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='is_service',
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('customer', '客户'), ('supplier', '供应商'), ('production', '生产商'), ('service', '运输/服务商'), ('invoice', '账单费用')], default='customer', max_length=20, verbose_name='伙伴类型'),
        ),
    ]
