# Generated by Django 2.1.2 on 2019-01-10 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0017_auto_20190110_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='公司资料'),
        ),
    ]
