# Generated by Django 2.1.2 on 2019-01-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0019_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MrpSupplier',
        ),
    ]
