# Generated by Django 2.1.2 on 2019-01-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0021_customer_mrpsupplier_supplier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partner',
            unique_together={('phone', 'name', 'province', 'city')},
        ),
    ]
