# Generated by Django 2.1.2 on 2018-12-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'customer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Partner', verbose_name='客户名称'),
        ),
    ]
