# Generated by Django 2.1.2 on 2018-12-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20181204_0531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={'ordering': ('line',), 'verbose_name': '销售订单行'},
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='piece',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='件'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='单价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='数量'),
        ),
    ]
