# Generated by Django 2.1.7 on 2019-03-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_auto_20190313_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLeads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vital', models.BooleanField(default=False, verbose_name='标注')),
                ('name', models.CharField(max_length=100, verbose_name='商机')),
                ('state', models.CharField(choices=[('0%', '失去'), ('10%', '新建'), ('30%', '验证'), ('70%', '跟进'), ('100%', '赢得')], default='10%', max_length=20, verbose_name='状态')),
                ('ps', models.CharField(blank=True, max_length=200, null=True, verbose_name='内部备注')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesleads_entry', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('handlers', models.ManyToManyField(related_name='salesleads_handler', to=settings.AUTH_USER_MODEL, verbose_name='经办人')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '销售线索',
            },
        ),
    ]
