# Generated by Django 2.1.2 on 2018-12-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20181206_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='piece',
            field=models.IntegerField(blank=True, null=True, verbose_name='件'),
        ),
    ]
