# Generated by Django 2.1.2 on 2018-12-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20181126_1554'),
        ('sales', '0004_auto_20181206_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Warehouse', verbose_name='出货仓库'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesorderitem_location', to='stock.Location', verbose_name='库位'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='location_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesorderitem_location_dest', to='stock.Location', verbose_name='目标库位'),
        ),
    ]
