# Generated by Django 2.1.7 on 2019-03-17 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190317_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesleads',
            name='pirce_gt',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格(止)'),
        ),
        migrations.AddField(
            model_name='salesleads',
            name='pirce_lt',
            field=models.IntegerField(blank=True, null=True, verbose_name='价格(起)'),
        ),
        migrations.AlterField(
            model_name='salesleads',
            name='handlers',
            field=models.ManyToManyField(related_name='salesleads_handler', to=settings.AUTH_USER_MODEL, verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='salesleads',
            name='is_vital',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
