# Generated by Django 2.1.2 on 2018-12-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20181206_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='warehouse',
        ),
    ]
