# Generated by Django 2.1.7 on 2019-03-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190317_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesleads',
            name='name',
        ),
    ]
