# Generated by Django 2.1.7 on 2019-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesleads_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesleads',
            name='miss_reason',
            field=models.CharField(blank=True, choices=[('价钱差距', '价钱差距'), ('质量不符合', '质量不符合'), ('工程流产', '工程流产'), ('工程暂停', '工程暂停'), ('换板', '换板')], max_length=60, null=True, verbose_name='错失原因'),
        ),
        migrations.AlterField(
            model_name='salesleads',
            name='state',
            field=models.CharField(choices=[('0%', '失去'), ('10%', '新线索'), ('30%', '取得确认'), ('70%', '报价阶段'), ('90%', '成功在望'), ('100%', '赢得')], default='10%', max_length=20, verbose_name='状态'),
        ),
    ]
