# Generated by Django 2.1.2 on 2018-12-10 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesorder_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner', verbose_name='客户名称'),
            preserve_default=False,
        ),
    ]
