# Generated by Django 2.1.2 on 2018-12-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20181210_1414'),
        ('sales', '0007_auto_20181210_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Area', verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.City', verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partner.Province', verbose_name='省份'),
        ),
    ]
