# Generated by Django 2.1.2 on 2018-12-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20181210_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorder',
            name='area',
        ),
    ]
