# Generated by Django 2.1.2 on 2018-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_salesorder_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品'),
        ),
    ]
