# Generated by Django 2.1.2 on 2018-12-19 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20181211_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type__in': ('block', 'slab')}, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='产品'),
        ),
    ]
