# Generated by Django 2.1.2 on 2019-01-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_auto_20190103_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='sales.Customer', verbose_name='客户名称'),
        ),
    ]
