# Generated by Django 2.1.2 on 2019-01-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20190108_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'type__in': ('block', 'slab')}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_order_item', to='product.Product', verbose_name='产品'),
        ),
    ]
