# Generated by Django 2.1.2 on 2019-01-15 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20190112_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_order', to='partner.Customer', verbose_name='客户名称'),
        ),
    ]
