# Generated by Django 2.1.2 on 2019-01-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20190115_0357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'permissions': (('can_audit', '审核'),), 'verbose_name': '销售订单'},
        ),
    ]
