# Generated by Django 2.1.2 on 2019-01-19 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_auto_20190115_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-date', '-created'], 'permissions': (('can_audit', '审核'),), 'verbose_name': '销售订单'},
        ),
    ]
