# Generated by Django 2.1.2 on 2019-03-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20190119_0348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesorder',
            options={'ordering': ['-date', '-id', '-created'], 'permissions': (('can_audit', '审核'),), 'verbose_name': '销售订单'},
        ),
    ]
